### ISSUE TITLE
TypeError: Harvest is not a constructor

### ISSUE THREAD

**Issue by sdelpuerto-intelygenz** [simplyspoke/node-harvest#108]
Node version: 8.9.3 / 10.7.0
Harvest version: 2.0.3

```
const Harvest = require('harvest')
const harvest = new Harvest({/* ... */})

// TypeError: Harvest is not a constructor
```

What's going on?

**Comment by simplyspoke** [comment]
Good question,

I am looking into the issue presently. Initial investigation would suggest a issue relating to recent automated updates. Will rebuild, test, and let you know.

**Comment by simplyspoke** [comment]
I have entirely shifted to import in most of my uses, so looks like I didn't properly test `require`. 

For the immediate moment, `const Harvest = require('harvest').default` should work. I will update the module loader shortly to support require.

Thank you for reporting this issue.

**Comment by sdelpuerto-intelygenz** [comment]
Yes, of course. Just hit me up when you publish and I'll gladly do the test.

**Comment by simplyspoke** [comment]
@sdelpuerto-intelygenz,

Version **2.1.1** should have what you need. Would have been patch version less, but in my thickness I pushed up the fix without including the new file in the publish.

Let me know if there is anything else.

**Comment by Jameskmonger** [comment]
This is still broken when using TypeScript.

The typings for `"harvest"` mean I have to import it as a default:

```
import Harvest from "harvest";

const harvest = new Harvest(...)
```

This then transpiles to:

```
var harvest_1 = require("harvest");
var harvest = new harvest_1["default"]({
```

However `harvest_1` is the `Harvest` constructor itself.

To fix this, the `/index.js` file needs to be deleted and `main` in `package.json` needs to be updated to point to `/dist/index.js`.

**Comment by Jameskmonger** [comment]
A workaround for now is to do the following:

```
const Harvest = require("harvest");

const harvest = new Harvest({
```

Downsides of this:
1. You must install `@types/node`
2. You don't get any typings for `Harvest`.

I have raised a fix in #112

**Comment by robinparisi** [comment]
I get the same error with version 2.2.3. Maybe a regression?

**Comment by simplyspoke** [comment]
I suspect as much. Will have to get some better testing in place and ensure proper support of both commonjs and ES6 imports.

**Comment by Jameskmonger** [comment]
I will investigate this shortly @simplyspoke

**Comment by Jameskmonger** [comment]
I'm not able to reproduce this @robinparisi. Here is my setup:

- `harvest@2.2.3`
- `typescript@3.0.3`

```typescript
import Harvest from "harvest";

const api = new Harvest({
    subdomain: 'mysubdomain',
    userAgent: 'myuseragent',
    concurrency: 1,
    auth: { accessToken, accountId } 
});

api.projectAssignments.me({})
    .then(assignments => console.log(assignments));
```

I get some assignments printed in the console. Would you mind sharing your setup?

**Comment by simplyspoke** [comment]
I believe those experiancing the issue are trying to us the module via commonjs, so it would be using require('harvest');

**Comment by Jameskmonger** [comment]
@robinparisi A workaround for now is this:

```
const Harvest = require("harvest").default;
```

I think some further investigation is needed to see how we can have an export which can be:

- imported in TypeScript like `import Harvest from "harvest";`
- imported in JavaScript like `const Harvest = require("harvest");`

There is a related issue on the TypeScript repo: https://github.com/Microsoft/TypeScript/issues/2719

[Anders Hejlsberg's response is a wontfix](https://github.com/Microsoft/TypeScript/issues/2719#issuecomment-92189669) - either ES6 exports or CommonJS, but not both

**Comment by simplyspoke** [comment]
I agree @Jameskmonger...

This is a rather lightweight and simple module, so throwing a bundler in front of the packaging process doesn't feel like it gets us much.

As for the imports, I tested both a ts file and js file just shifting the module loader and it looks like it should fix both needs well. Would like to get a better eye on it before pushing up the changes as I only had 15min to test my approach. Might be nice to pair with pulling out webpack.

**Comment by Jameskmonger** [comment]
I do notice [here](https://github.com/jsforum/jsforum/issues/5) that `jsnext:main` has been superseded by the `module` property anyway. Do you still think it's worth having both? Maybe for people on older versions.

**Comment by simplyspoke** [comment]
I like having that bit of backwards compatibility. If it reduces the chance people with have any issues, seems like a win.

**Comment by simplyspoke** [comment]
@robinparisi I believe that 2.2.4 should support require now.
